### ISSUE TITLE
修改rule.json就会404

### ISSUE THREAD

**Issue by sjkgames** [dengyuhan/magnetW#22]
> 操作系统版本：
>Centos7
> 磁力搜版本：  
>2.0.5
> 问题描述：  
>修改rule.json后就会显示404，重启tomcat也无效。
哪怕只是修改一个网址也会404报错，不清楚问题出在哪里，但是保持原来的内容就正常。
改完就显示这个
HTTP Status 404 – Not Found
Type Status Report

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/9.0.0.M18
> 异常日志（如果有）：

**Comment by dengyuhan** [comment]
tomcat启动过程中有报错吗

**Comment by sjkgames** [comment]
[ERROR]----[2019-06-23 01:17:55:029]----[in.xiandan.magnetw.handler.GlobalExceptionHandler.handleException(GlobalExceptionHandler.java:28)]
HTTP error fetching URL


org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://www.122774.com/search/%E9%92%A2%E9%93%81%E4%BE%A0/1
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:776)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:722)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:306)
	at in.xiandan.magnetw.service.MagnetService.parser(MagnetService.java:146)
	at in.xiandan.magnetw.service.MagnetService$$FastClassBySpringCGLIB$$cf9298ad.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:414)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at in.xiandan.magnetw.service.MagnetService$$EnhancerBySpringCGLIB$$894fdfc1.parser(<generated>)
	at in.xiandan.magnetw.controller.MagnetApiController.search(MagnetApiController.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at in.xiandan.magnetw.filter.RequestLoggerFilter.doFilterInternal(RequestLoggerFilter.java:43)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:475)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:495)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:767)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1354)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)







------------------ 原始邮件 ------------------
发件人: "denghaha"<notifications@github.com>; 
发送时间: 2019年6月23日(星期天) 凌晨1:13
收件人: "dengyuhan/magnetW"<magnetW@noreply.github.com>; 
抄送: "Trojan Knife"<376686131@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dengyuhan/magnetW] 修改rule.json就会404 (#22)




tomcat启动过程中有报错吗

**Comment by dengyuhan** [comment]
规则没写对，参考现有规则和[文档](https://github.com/dengyuhan/magnetW/blob/master/Config.md#%E8%A7%84%E5%88%99%E8%AF%B4%E6%98%8E)

**Comment by sjkgames** [comment]
是要每一条全要正确才能跑的起来是么？




------------------ 原始邮件 ------------------
发件人: "denghaha"<notifications@github.com>; 
发送时间: 2019年6月23日(星期天) 凌晨1:33
收件人: "dengyuhan/magnetW"<magnetW@noreply.github.com>; 
抄送: "Trojan Knife"<376686131@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dengyuhan/magnetW] 修改rule.json就会404 (#22)




规则没写对，参考现有规则和文档

**Comment by dengyuhan** [comment]
可以跑起来但搜不到东西

你给的异常信息是搜索报出的

**Comment by sjkgames** [comment]
这个是localhost的日志，正常来说只修改一处肯定是跑的起来的，但是我这只修改了rule.json就报错了，是还需要修改哪处吗23-Jun-2019 01:35:10.270 INFO [main] org.apache.catalina.core.ApplicationContext.log Set web app root system property: 'magnetw' = [/www/server/tomcat/webapps/root/]
23-Jun-2019 01:35:10.271 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing log4j from [/www/server/tomcat/webapps/root/WEB-INF/log4j.properties]
23-Jun-2019 01:35:10.456 INFO [main] org.apache.catalina.core.ApplicationContext.log Shutting down log4j
23-Jun-2019 01:35:10.459 INFO [main] org.apache.catalina.core.ApplicationContext.log Closing Spring root WebApplicationContext
23-Jun-2019 01:35:11.641 INFO [main] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath
23-Jun-2019 01:35:11.678 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
23-Jun-2019 01:35:14.588 INFO [main] org.apache.catalina.core.ApplicationContext.log Set web app root system property: 'magnetw' = [/www/server/tomcat/webapps/magnetw-2.0.5/]
23-Jun-2019 01:35:14.589 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing log4j from [/www/server/tomcat/webapps/magnetw-2.0.5/WEB-INF/log4j.properties]
23-Jun-2019 01:35:14.669 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring FrameworkServlet 'dispatcher'
23-Jun-2019 01:35:16.347 INFO [main] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath
23-Jun-2019 01:35:16.385 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
23-Jun-2019 01:35:18.464 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.springframework.web.util.Log4jConfigListener
 java.lang.IllegalStateException: Web app root system property already set to different value: 'magnetw' = [/www/server/tomcat/webapps/magnetw-2.0.5/] instead of [/www/server/tomcat/webapps/root1/] - Choose unique values for the 'webAppRootKey' context-param in your web.xml files!
	at org.springframework.web.util.WebUtils.setWebAppRootSystemProperty(WebUtils.java:162)
	at org.springframework.web.util.Log4jWebConfigurer.initLogging(Log4jWebConfigurer.java:119)
	at org.springframework.web.util.Log4jConfigListener.contextInitialized(Log4jConfigListener.java:49)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4744)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5206)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1107)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1841)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1019)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:409)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1551)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:284)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:976)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1439)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1429)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:953)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:793)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:655)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.daemon.support.DaemonLoader.start(DaemonLoader.java:243)


23-Jun-2019 01:35:18.468 INFO [main] org.apache.catalina.core.ApplicationContext.log Shutting down log4j
23-Jun-2019 01:35:18.472 INFO [main] org.apache.catalina.core.ApplicationContext.log Closing Spring root WebApplicationContext
23-Jun-2019 01:35:18.649 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
23-Jun-2019 01:35:18.649 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
23-Jun-2019 01:35:19.837 INFO [main] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath
23-Jun-2019 01:35:19.883 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
23-Jun-2019 01:35:21.124 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
 org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'indexController': Unsatisfied dependency expressed through field 'ruleService': Error creating bean with name 'magnetRuleService': Invocation of init method failed; nested exception is com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 37 column 24 path $[2].group; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'magnetRuleService': Invocation of init method failed; nested exception is com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 37 column 24 path $[2].group
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4744)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5206)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1107)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1841)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1019)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:409)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1551)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:284)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:976)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1439)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1429)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:953)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:793)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:655)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.daemon.support.DaemonLoader.start(DaemonLoader.java:243)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'magnetRuleService': Invocation of init method failed; nested exception is com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 37 column 24 path $[2].group
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:187)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1213)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1053)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1018)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
	... 60 more
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 37 column 24 path $[2].group
	at com.google.gson.Gson.fromJson(Gson.java:903)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at in.xiandan.magnetw.service.MagnetRuleService.loadResourceMagnetRule(MagnetRuleService.java:217)
	at in.xiandan.magnetw.service.MagnetRuleService.loadMagnetRule(MagnetRuleService.java:204)
	at in.xiandan.magnetw.service.MagnetRuleService.getMagnetRule(MagnetRuleService.java:138)
	at in.xiandan.magnetw.service.MagnetRuleService.reload(MagnetRuleService.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:310)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 73 more
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 37 column 24 path $[2].group
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:214)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	... 85 more


23-Jun-2019 01:35:21.129 INFO [main] org.apache.catalina.core.ApplicationContext.log Set web app root system property: 'magnetw' = [/www/server/tomcat/webapps/root/]
23-Jun-2019 01:35:21.130 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing log4j from [/www/server/tomcat/webapps/root/WEB-INF/log4j.properties]
23-Jun-2019 01:35:21.180 INFO [main] org.apache.catalina.core.ApplicationContext.log Shutting down log4j
23-Jun-2019 01:35:21.183 INFO [main] org.apache.catalina.core.ApplicationContext.log Closing Spring root WebApplicationContext





------------------ 原始邮件 ------------------
发件人: "denghaha"<notifications@github.com>; 
发送时间: 2019年6月23日(星期天) 凌晨1:35
收件人: "dengyuhan/magnetW"<magnetW@noreply.github.com>; 
抄送: "Trojan Knife"<376686131@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dengyuhan/magnetW] 修改rule.json就会404 (#22)




可以跑起来但搜不到东西
 
你给的异常信息是搜索报出的

**Comment by dengyuhan** [comment]
你的规则有问题，不是正确的JSON格式，[json.cn](https://www.json.cn)可以检查格式

**Comment by sjkgames** [comment]
我获取www.122774.com的group得到//*[@id="content"]/div/dl，但是json怎么样都是报错的。。不是很明白为什么



------------------ 原始邮件 ------------------
发件人: "denghaha"<notifications@github.com>; 
发送时间: 2019年6月23日(星期天) 凌晨1:47
收件人: "dengyuhan/magnetW"<magnetW@noreply.github.com>; 
抄送: "Trojan Knife"<376686131@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dengyuhan/magnetW] 修改rule.json就会404 (#22)




你的规则有问题，不是正确的JSON格式，json.cn可以检查格式

**Comment by dengyuhan** [comment]
双引号需要转义，现有的规则应该有类似的
