### ISSUE TITLE
1.1.4war包部署解析失败

### ISSUE THREAD

**Issue by exrock** [dengyuhan/magnetW#4]
搜索时提示"解析失败"，几个接口都一样，地址：https://cili.myhost.pw/magnetw-1.1.4/

**Comment by dengyuhan** [comment]
解析失败一般是抛了异常，贴一下错误日志

**Comment by exrock** [comment]
似乎这里除了问题：

> org.springframework.expression.spel.SpelEvaluationException: EL1007E:(pos 10): Property or field 'source' cannot be found on null


`
sh-4.3# ls
catalina.2018-09-06.log      localhost.2018-09-06.log		  manager.2018-09-06.log
catalina.out		     localhost_access_log.2018-09-06.txt
host-manager.2018-09-06.log  magnetw
sh-4.3# 
sh-4.3# 
sh-4.3# 
sh-4.3# cat catalina.out 
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version:        Apache Tomcat/7.0.82
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built:          Sep 29 2017 12:23:15 UTC
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server number:         7.0.82.0
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name:               Linux
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Version:            3.10.105
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Architecture:          amd64
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Java Home:             /volume1/@appstore/Java8/j2sdk-image/jre
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Version:           1.8.0_161-b12
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor:            Oracle Corporation
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_BASE:         /var/packages/Tomcat7/target/src
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_HOME:         /var/packages/Tomcat7/target/src
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.util.logging.config.file=/var/packages/Tomcat7/target/src/conf/logging.properties
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Xms32m
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Xmx1953m
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.endorsed.dirs=/var/packages/Tomcat7/target/src/endorsed
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.base=/var/packages/Tomcat7/target/src
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.home=/var/packages/Tomcat7/target/src
Sep 06, 2018 12:20:21 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.io.tmpdir=/var/packages/Tomcat7/target/src/temp
Sep 06, 2018 12:20:21 AM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
Sep 06, 2018 12:20:22 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-7070"]
Sep 06, 2018 12:20:22 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-bio-8009"]
Sep 06, 2018 12:20:22 AM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 983 ms
Sep 06, 2018 12:20:22 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Sep 06, 2018 12:20:22 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.82
Sep 06, 2018 12:20:22 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /volume1/tomcat/magnetw-1.1.4.war
Sep 06, 2018 12:20:22 AM org.apache.catalina.loader.WebappClassLoaderBase validateJarFile
INFO: validateJarFile(/var/packages/Tomcat7/target/src/webapps/magnetw-1.1.4/WEB-INF/lib/javax.el-api-3.0.0.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/el/Expression.class
Sep 06, 2018 12:20:22 AM org.apache.catalina.loader.WebappClassLoaderBase validateJarFile
INFO: validateJarFile(/var/packages/Tomcat7/target/src/webapps/magnetw-1.1.4/WEB-INF/lib/jsp-api-2.1.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/el/Expression.class
Sep 06, 2018 12:20:22 AM org.apache.catalina.loader.WebappClassLoaderBase validateJarFile
INFO: validateJarFile(/var/packages/Tomcat7/target/src/webapps/magnetw-1.1.4/WEB-INF/lib/servlet-api-2.5.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
Sep 06, 2018 12:20:22 AM org.apache.catalina.deploy.WebXml setVersion
WARNING: Unknown version string [3.1]. Default version will be used.
Sep 06, 2018 12:20:24 AM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j:WARN No appenders could be found for logger (org.springframework.web.context.ContextLoader).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Sep 06, 2018 12:20:28 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /volume1/tomcat/magnetw-1.1.4.war has finished in 5,829 ms
Sep 06, 2018 12:20:28 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /volume1/tomcat/docs
Sep 06, 2018 12:20:28 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /volume1/tomcat/docs has finished in 117 ms
Sep 06, 2018 12:20:28 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /volume1/tomcat/host-manager
Sep 06, 2018 12:20:28 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /volume1/tomcat/host-manager has finished in 67 ms
Sep 06, 2018 12:20:28 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /volume1/tomcat/manager
Sep 06, 2018 12:20:28 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /volume1/tomcat/manager has finished in 46 ms
Sep 06, 2018 12:20:28 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-7070"]
Sep 06, 2018 12:20:28 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8009"]
Sep 06, 2018 12:20:28 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 6223 ms
[INFO ]----[2018-09-06 00:24:41:917]----[com.dyhdyh.magnetw.controller.BaseController.logger(BaseController.java:22)]
http://cili.myhost.pw/magnetw-1.1.4/api/search?source=种子搜&keyword=test&page=1

org.springframework.expression.spel.SpelEvaluationException: EL1007E:(pos 10): Property or field 'source' cannot be found on null
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:220)
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:94)
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.access$000(PropertyOrFieldReference.java:46)
	at org.springframework.expression.spel.ast.PropertyOrFieldReference$AccessorLValue.getValue(PropertyOrFieldReference.java:374)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
	at org.springframework.expression.spel.ast.MethodReference.getArguments(MethodReference.java:154)
	at org.springframework.expression.spel.ast.MethodReference.getValueRef(MethodReference.java:71)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:66)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:87)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:120)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:242)
	at org.springframework.cache.interceptor.CacheOperationExpressionEvaluator.key(CacheOperationExpressionEvaluator.java:117)
	at org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContext.generateKey(CacheAspectSupport.java:738)
	at org.springframework.cache.interceptor.CacheAspectSupport.generateKey(CacheAspectSupport.java:554)
	at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:498)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:389)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at com.dyhdyh.magnetw.service.MagnetWService$$EnhancerBySpringCGLIB$$ccb8f588.parser(<generated>)
	at com.dyhdyh.magnetw.controller.MagnetWController.getSearchMagnetJson(MagnetWController.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[INFO ]----[2018-09-06 00:26:06:399]----[com.dyhdyh.magnetw.controller.BaseController.logger(BaseController.java:22)]
http://cili.myhost.pw/magnetw-1.1.4/api/search?source=种子搜&keyword=test&page=1

org.springframework.expression.spel.SpelEvaluationException: EL1007E:(pos 10): Property or field 'source' cannot be found on null
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:220)
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:94)
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.access$000(PropertyOrFieldReference.java:46)
	at org.springframework.expression.spel.ast.PropertyOrFieldReference$AccessorLValue.getValue(PropertyOrFieldReference.java:374)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
	at org.springframework.expression.spel.ast.MethodReference.getArguments(MethodReference.java:154)
	at org.springframework.expression.spel.ast.MethodReference.getValueRef(MethodReference.java:71)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:66)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:87)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:120)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:242)
	at org.springframework.cache.interceptor.CacheOperationExpressionEvaluator.key(CacheOperationExpressionEvaluator.java:117)
	at org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContext.generateKey(CacheAspectSupport.java:738)
	at org.springframework.cache.interceptor.CacheAspectSupport.generateKey(CacheAspectSupport.java:554)
	at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:498)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:389)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at com.dyhdyh.magnetw.service.MagnetWService$$EnhancerBySpringCGLIB$$ccb8f588.parser(<generated>)
	at com.dyhdyh.magnetw.controller.MagnetWController.getSearchMagnetJson(MagnetWController.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[INFO ]----[2018-09-06 00:26:19:887]----[com.dyhdyh.magnetw.controller.BaseController.logger(BaseController.java:22)]
http://cili.myhost.pw/magnetw-1.1.4/api/search?source=磁力吧&keyword=test&page=1

org.springframework.expression.spel.SpelEvaluationException: EL1007E:(pos 10): Property or field 'source' cannot be found on null
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:220)
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:94)
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.access$000(PropertyOrFieldReference.java:46)
	at org.springframework.expression.spel.ast.PropertyOrFieldReference$AccessorLValue.getValue(PropertyOrFieldReference.java:374)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
	at org.springframework.expression.spel.ast.MethodReference.getArguments(MethodReference.java:154)
	at org.springframework.expression.spel.ast.MethodReference.getValueRef(MethodReference.java:71)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:66)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:87)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:120)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:242)
	at org.springframework.cache.interceptor.CacheOperationExpressionEvaluator.key(CacheOperationExpressionEvaluator.java:117)
	at org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContext.generateKey(CacheAspectSupport.java:738)
	at org.springframework.cache.interceptor.CacheAspectSupport.generateKey(CacheAspectSupport.java:554)
	at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:498)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:389)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at com.dyhdyh.magnetw.service.MagnetWService$$EnhancerBySpringCGLIB$$ccb8f588.parser(<generated>)
	at com.dyhdyh.magnetw.controller.MagnetWController.getSearchMagnetJson(MagnetWController.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
sh-4.3# 
sh-4.3# 
sh-4.3# 
sh-4.3# ls
catalina.2018-09-06.log      localhost.2018-09-06.log		  manager.2018-09-06.log
catalina.out		     localhost_access_log.2018-09-06.txt
host-manager.2018-09-06.log  magnetw
sh-4.3# cat localhost_access_log.2018-09-06.txt 
127.0.0.1 - - [06/Sep/2018:00:23:29 +0800] "GET /magnetw-1.1.4/ HTTP/1.1" 200 13293
127.0.0.1 - - [06/Sep/2018:00:23:29 +0800] "GET /magnetw-1.1.4/resources/css/bootstrap.min.css HTTP/1.1" 200 121200
127.0.0.1 - - [06/Sep/2018:00:23:29 +0800] "GET /magnetw-1.1.4/resources/css/base.css HTTP/1.1" 200 120
127.0.0.1 - - [06/Sep/2018:00:23:29 +0800] "GET /magnetw-1.1.4/resources/css/search_result.css HTTP/1.1" 200 586
127.0.0.1 - - [06/Sep/2018:00:23:29 +0800] "GET /magnetw-1.1.4/resources/js/dist/vue-clipboard.min.js HTTP/1.1" 200 13209
127.0.0.1 - - [06/Sep/2018:00:23:29 +0800] "GET /magnetw-1.1.4/api/source-site HTTP/1.1" 200 79
127.0.0.1 - - [06/Sep/2018:00:23:30 +0800] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [06/Sep/2018:00:24:42 +0800] "GET /magnetw-1.1.4/api/search?source=%E7%A7%8D%E5%AD%90%E6%90%9C&keyword=test&page=1 HTTP/1.1" 200 47
127.0.0.1 - - [06/Sep/2018:00:26:06 +0800] "GET /magnetw-1.1.4/api/search?source=%E7%A7%8D%E5%AD%90%E6%90%9C&keyword=test&page=1 HTTP/1.1" 200 47
127.0.0.1 - - [06/Sep/2018:00:26:19 +0800] "GET /magnetw-1.1.4/api/search?source=%E7%A3%81%E5%8A%9B%E5%90%A7&keyword=test&page=1 HTTP/1.1" 200 47
sh-4.3# 
sh-4.3# 
sh-4.3# cat magnetw/magnetw.
magnetw.error.log  magnetw.log        
sh-4.3# cat magnetw/magnetw.error.log 
sh-4.3# cat magnetw/magnetw.log 
[INFO ]----[2018-09-06 00:24:41:917]----[com.dyhdyh.magnetw.controller.BaseController.logger(BaseController.java:22)]----http://cili.myhost.pw/magnetw-1.1.4/api/search?source=种子搜&keyword=test&page=1
[INFO ]----[2018-09-06 00:26:06:399]----[com.dyhdyh.magnetw.controller.BaseController.logger(BaseController.java:22)]----http://cili.myhost.pw/magnetw-1.1.4/api/search?source=种子搜&keyword=test&page=1
[INFO ]----[2018-09-06 00:26:19:887]----[com.dyhdyh.magnetw.controller.BaseController.logger(BaseController.java:22)]----http://cili.myhost.pw/magnetw-1.1.4/api/search?source=磁力吧&keyword=test&page=1
sh-4.3# 
sh-4.3# 
sh-4.3# 
`

**Comment by dengyuhan** [comment]
出现这个异常是因为在json里找不到对应的网站名称，有可能是因为环境导致中文乱码查不到json里对应的规则，建议先用源码调试
[MagnetWController.getMagnetRule()](https://github.com/dengyuhan/magnetW/blob/master/src/main/java/com/dyhdyh/magnetw/controller/MagnetWController.java)
